import type { APIRoute } from 'astro';

export const GET: APIRoute = () => {
  const siteUrl = 'https://joburgchurch.co.za';
  const now = '2026-10-05';

  const staticPages = [
    { url: '/', priority: '1.0', changefreq: 'weekly' },
    { url: '/about/', priority: '0.8', changefreq: 'monthly' },
    { url: '/visit/', priority: '0.9', changefreq: 'monthly' },
    { url: '/community-classes/', priority: '0.9', changefreq: 'weekly' },
    { url: '/community-classes/korean/', priority: '0.9', changefreq: 'weekly' },
    { url: '/spiritual-education/', priority: '0.9', changefreq: 'weekly' },
    { url: '/youth-usecan/', priority: '0.8', changefreq: 'monthly' },
    { url: '/sermons/', priority: '0.7', changefreq: 'weekly' },
    { url: '/videos/', priority: '0.9', changefreq: 'weekly' },
    { url: '/events/', priority: '0.7', changefreq: 'weekly' },
    { url: '/gallery/', priority: '0.6', changefreq: 'monthly' },
    { url: '/blog/', priority: '0.9', changefreq: 'weekly' },
    { url: '/faq/', priority: '0.8', changefreq: 'monthly' },
    { url: '/contact/', priority: '0.8', changefreq: 'monthly' },
    { url: '/privacy/', priority: '0.3', changefreq: 'yearly' },
    { url: '/locations/', priority: '0.8', changefreq: 'weekly' },
    { url: '/locations/sandton/', priority: '0.9', changefreq: 'weekly' },
    { url: '/locations/randburg/', priority: '0.7', changefreq: 'monthly' },
    { url: '/locations/fourways/', priority: '0.7', changefreq: 'monthly' },
    { url: '/locations/midrand/', priority: '0.7', changefreq: 'monthly' },
    { url: '/locations/alberton/', priority: '0.7', changefreq: 'monthly' },
    { url: '/locations/roodepoort/', priority: '0.7', changefreq: 'monthly' },
    { url: '/locations/soweto/', priority: '0.7', changefreq: 'monthly' },
    { url: '/churches-in-johannesburg/', priority: '0.8', changefreq: 'monthly' },
  ];

  // Phase 10 SEO landing pages — added 2026-07-03
  const seoLandingPages = [
    { url: '/free-bible-study-sandton/', lastmod: '2026-07-03' },
    { url: '/online-bible-study-johannesburg/', lastmod: '2026-07-03' },
    { url: '/korean-language-class-for-beginners-johannesburg/', lastmod: '2026-07-03' },
    { url: '/what-to-wear-to-church-johannesburg/', lastmod: '2026-07-03' },
    { url: '/first-time-church-visitor-johannesburg/', lastmod: '2026-07-03' },
    { url: '/church-service-times-sandton/', lastmod: '2026-07-03' },
    { url: '/free-korean-class-johannesburg/', lastmod: '2026-10-01' },
    { url: '/youth-bible-study-johannesburg/', lastmod: '2026-07-03' },
    { url: '/churches-in-sandton/', lastmod: '2026-07-03' },
    { url: '/bible-study-for-depression-johannesburg/', lastmod: '2026-07-03' },
    { url: '/marriage-counselling-johannesburg/', lastmod: '2026-07-03' },
    { url: '/parenting-biblical-advice-johannesburg/', lastmod: '2026-07-03' },
    { url: '/youth-ministry-johannesburg-usecan/', lastmod: '2026-07-03' },
    { url: '/bible-study-randburg/', lastmod: '2026-07-03' },
    { url: '/bible-study-fourways/', lastmod: '2026-07-03' },
    { url: '/bible-study-midrand/', lastmod: '2026-07-03' },
    { url: '/bible-study-alberton/', lastmod: '2026-07-03' },
    { url: '/bible-study-roodepoort/', lastmod: '2026-07-03' },
    { url: '/bible-study-soweto/', lastmod: '2026-07-03' },
  ];

  const blogPosts = [
    { url: '/blog/welcome-to-our-church/', lastmod: '2026-01-01' },
    { url: '/blog/korean-class-community/', lastmod: '2026-10-01' },
    { url: '/blog/why-community-learning-matters/', lastmod: '2026-03-01' },
    { url: '/blog/youth-growth-spiritual-education/', lastmod: '2026-04-01' },
    { url: '/blog/how-to-join-online-bible-study/', lastmod: '2026-05-01' },
    { url: '/blog/what-to-expect-first-bible-study/', lastmod: '2026-06-10' },
    { url: '/blog/learning-korean-as-an-adult-sandton/', lastmod: '2026-06-15' },
    { url: '/blog/finding-community-as-a-young-adult-johannesburg/', lastmod: '2026-06-20' },
    { url: '/blog/bible-study-near-me-johannesburg/', lastmod: '2026-06-25' },
    { url: '/blog/when-the-bible-feels-irrelevant/', lastmod: '2026-07-05' },
    { url: '/blog/what-sandton-gets-wrong-about-christianity/', lastmod: '2026-07-08' },
    { url: '/blog/the-gospel-according-to-load-shedding/', lastmod: '2026-07-10' },
    { url: '/blog/why-online-bible-study-johannesburg/', lastmod: '2026-07-18' },
    { url: '/blog/free-korean-class-sandton-johannesburg/', lastmod: '2026-07-18' },
    { url: '/blog/first-time-bible-study-what-to-expect/', lastmod: '2026-07-18' },
    { url: '/blog/find-right-church-johannesburg/', lastmod: '2026-07-18' },
    { url: '/blog/church-near-me-sandton/', lastmod: '2026-07-18' },
    { url: '/blog/online-church-johannesburg/', lastmod: '2026-07-18' },
    { url: '/blog/christian-community-johannesburg/', lastmod: '2026-07-18' },
    { url: '/blog/ubuntu-and-christianity-south-africa/', lastmod: '2026-07-21' },
    { url: '/blog/load-shedding-bible-study-guide-south-africa/', lastmod: '2026-07-21' },
    { url: '/blog/township-bible-study-soweto-alexandra/', lastmod: '2026-07-21' },
    { url: '/blog/heritage-day-christian-reflection/', lastmod: '2026-07-21' },
    { url: '/blog/multilingual-worship-johannesburg/', lastmod: '2026-07-21' },
    { url: '/blog/jozi-young-professionals-bible-study/', lastmod: '2026-07-21' },
    { url: '/blog/joburg-rainy-season-quiet-time/', lastmod: '2026-07-23' },
    { url: '/blog/reading-bible-second-language-johannesburg/', lastmod: '2026-07-23' },
    { url: '/blog/commuter-prayer-johannesburg-guide/', lastmod: '2026-07-23' },
    { url: '/blog/winter-funerals-south-africa-grief/', lastmod: '2026-07-23' },
    { url: '/blog/mid-year-reset-july-spiritual-check-in/', lastmod: '2026-07-23' },
    { url: '/blog/waiting-on-god-johannesburg-delays/', lastmod: '2026-07-25' },
    { url: '/blog/caring-aging-parents-south-africa/', lastmod: '2026-07-25' },
    { url: '/blog/moving-to-johannesburg-newcomers/', lastmod: '2026-07-25' },
    { url: '/blog/single-adults-faith-johannesburg/', lastmod: '2026-07-25' },
    { url: '/blog/money-stewardship-south-african-christians/', lastmod: '2026-07-25' },
    { url: '/blog/hospital-visit-south-africa-christian/', lastmod: '2026-07-30' },
    { url: '/blog/raising-children-faith-multilingual-south-africa/', lastmod: '2026-07-30' },
    { url: '/blog/forgiveness-south-africa-historical-weight/', lastmod: '2026-07-30' },
    { url: '/blog/discerning-false-teachers-south-africa/', lastmod: '2026-07-30' },
    { url: '/blog/intergenerational-discipleship-south-africa/', lastmod: '2026-07-30' },
    { url: '/blog/heritage-month-south-africa-memory/', lastmod: '2026-09-20' },
    { url: '/blog/joburg-spring-new-seasons-bible/', lastmod: '2026-09-20' },
    { url: '/blog/sandton-soweto-gospel-gap/', lastmod: '2026-09-20' },
    { url: '/blog/trust-honesty-south-africa-christian/', lastmod: '2026-09-20' },
    { url: '/blog/peace-uncertainty-johannesburg-christian/', lastmod: '2026-09-20' },
    { url: '/blog/sabbath-rest-johannesburg-city-never-stops/', lastmod: '2026-09-27' },
    { url: '/blog/christian-grandparent-johannesburg-faith-2026/', lastmod: '2026-09-27' },
    { url: '/blog/helping-children-hard-news-south-africa/', lastmod: '2026-09-27' },
    { url: '/blog/christian-wedding-marriage-preparation-johannesburg/', lastmod: '2026-09-27' },
    { url: '/blog/lunch-break-bible-study-sandton-workplace/', lastmod: '2026-09-27' },
    // 30 September 2026 Chinese-language posts for South African Chinese Christian community
    { url: '/blog/nanfei-huaren-jiaohui-zhunanjohannesburg-zhongwen-jidutuanfei/', lastmod: '2026-09-30' },
    { url: '/blog/nanfei-waipai-huaren-jidutuan-shenghuo-johannesburg/', lastmod: '2026-09-30' },
    { url: '/blog/taiwanese-christians-south-africa-johannesburg/', lastmod: '2026-09-30' },
    { url: '/blog/nanfei-huayi-erda-xinyang-shenfen-jiaohui/', lastmod: '2026-09-30' },
    { url: '/blog/nanfei-mianfei-xinli-zixun-huaren-jidutuan/', lastmod: '2026-09-30' },
    { url: '/blog/yuebao-huaren-libai-juhui-dian-zhinan/', lastmod: '2026-09-30' },
    { url: '/blog/nanfei-shengfen-huaren-jidutuan-ziyuan/', lastmod: '2026-09-30' },
    { url: '/blog/nanfei-huaren-hunyin-jiating-jiaohui/', lastmod: '2026-09-30' },
    { url: '/blog/nanfei-zuolibai-shicao-zhinan/', lastmod: '2026-09-30' },
    { url: '/blog/yuebao-huaren-chajingban-zhouwu/', lastmod: '2026-09-30' },
    { url: '/blog/nanfei-anquan-xinyang-jidutuan/', lastmod: '2026-09-30' },
    { url: '/blog/nanfei-zhichang-xinyang-jidutuan/', lastmod: '2026-09-30' },
    // 01 October 2026 South Africa localised English posts
    { url: '/blog/diwali-festival-south-africa-christian-neighbour/', lastmod: '2026-10-01' },
    { url: '/blog/johannesburg-water-crisis-faith-day-zero-memories/', lastmod: '2026-10-01' },
    { url: '/blog/south-african-braai-and-the-table-grace/', lastmod: '2026-10-01' },
    { url: '/blog/retirement-village-faith-johannesburg-elderly/', lastmod: '2026-10-01' },
    { url: '/blog/returning-to-church-after-long-absence-johannesburg/', lastmod: '2026-10-01' },
    // 01 October 2026 Chinese-language posts for South African Chinese Christian community
    { url: '/blog/nanfei-liuxuesheng-jidutuan-shenghuo/', lastmod: '2026-10-01' },
    { url: '/blog/nanfei-waipai-zinv-jidutuan-jiaoyu/', lastmod: '2026-10-01' },
    { url: '/blog/nanfei-danshen-fumu-jidutuan-yangyu/', lastmod: '2026-10-01' },
    { url: '/blog/nanfei-yuancheng-bangong-xinyang-jidutuan/', lastmod: '2026-10-01' },
    { url: '/blog/nanfei-zhongzi-qiye-jidutuan-zhiye/', lastmod: '2026-10-01' },
    // 01 October 2026 South Africa localised hot-topic posts (jacarandas/spring)
    { url: '/blog/jacarandas-spring-joburg-second-bloom/', lastmod: '2026-10-01' },
    { url: '/blog/joburg-spring-gardening-faith-cultivation/', lastmod: '2026-10-01' },
    { url: '/blog/first-thunderstorm-spring-joburg-faith/', lastmod: '2026-10-01' },
    { url: '/blog/october-light-and-late-sundown-joburg/', lastmod: '2026-10-01' },
    { url: '/blog/spring-cleaning-home-and-soul-johannesburg/', lastmod: '2026-10-01' },
    // 01 October 2026 Chinese-language hot-topic posts (gold visa/return + dual language)
    { url: '/blog/nanfei-jinpian-haigui-jidutuan-shenfen/', lastmod: '2026-10-01' },
    { url: '/blog/nanfei-haiwai-qiaomin-laohui-jiating-jiuye/', lastmod: '2026-10-01' },
    { url: '/blog/nanfei-haigui-jidutuan-laoling-jihua/', lastmod: '2026-10-01' },
    { url: '/blog/nanfei-haizi-zhongwen-jiaoyu-shuangyu-qiehuan/', lastmod: '2026-10-01' },
    { url: '/blog/nanfei-luoye-gengen-jidutuan-shenfen/', lastmod: '2026-10-01' },
    // 05 October 2026 — South Africa localised high-value posts (Reddit research based, no controversy)
    { url: '/blog/money-and-the-south-african-christian-biblical-view/', lastmod: '2026-10-05' },
    { url: '/blog/mental-health-and-faith-johannesburg-christian/', lastmod: '2026-10-05' },
    { url: '/blog/finding-a-bible-based-community-johannesburg/', lastmod: '2026-10-05' },
    { url: '/blog/christian-expat-faith-johannesburg-multilingual/', lastmod: '2026-10-05' },
    { url: '/blog/small-church-vs-mega-church-south-africa-honest-reflection/', lastmod: '2026-10-05' },
    { url: '/blog/adult-child-still-depends-on-parents/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/anxiety-and-the-south-african-christian/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/being-a-christian-in-the-police/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/being-a-good-neighbour/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/being-the-only-christian-in-the-family/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/blended-family-south-africa/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/boomerang-generation-children-returning-home/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/burnout-and-the-south-african-christian/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/choosing-a-school-in-johannesburg/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/christian-and-the-2026-south-african-budget/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/christian-and-the-addiction-in-south-africa/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/christian-and-the-farm/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/christian-and-the-load-shedding-evening/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/christian-and-the-n1-traffic-spiritual-discipline/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/christian-and-the-pet/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/christian-and-the-pharmacist-shelf/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/christian-and-the-south-african-teen-pregnancy/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/christian-husband-spiritual-leadership/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/christian-pilgrim-in-the-coffee-shop/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/christian-reading-the-daily-newspaper/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/christian-witness-on-social-media/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/debt-and-the-christian/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/entrepreneur-and-the-gospel/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/exam-anxiety-and-the-south-african-christian-student/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/faithful-wife-struggling-husband/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/family-expectations-and-the-christian/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/first-time-church-visitor-who-understands-nothing/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/gardening-and-the-soul/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/gossip-and-the-christian-in-south-africa/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/hospitality-in-a-world-of-locked-doors/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/household-help-boundaries/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/loneliness-in-the-big-city/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/marriage-after-the-honeymoon-johannesburg/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/medical-crisis-and-the-christian/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/navigating-church-conflict-when-someone-hurts-you/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/new-neighbour-who-doesnt-fit/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/npo-and-church-charity-in-south-africa/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/online-bible-study-discipline-in-2026/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/pet-loss-and-the-christian/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/remarriage-after-divorce/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/small-group-commitment/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/south-african-christian-and-the-corporate-team/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/south-african-christian-and-the-driving-lesson/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/south-african-christian-and-the-economy/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/south-african-christian-and-the-school-fees/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/south-african-christian-reading-plan/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/step-parenting-in-south-africa/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/teenagers-and-the-bible-in-sandton/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-bereaved-grandparent-johannesburg/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-bible-translation-you-read/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-bride-who-changed-her-mind/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-christian-after-the-accident/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-christian-and-the-ai/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-christian-and-the-chronic-illness/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-christian-and-the-mental-load/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-christian-and-the-pension-fund/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-christian-artist/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-christian-doctor-in-johannesburg/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-christian-domestic-worker-and-the-employer/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-christian-father-who-works-too-much/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-christian-going-back-to-school/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-christian-grandparent-discipling-grandchildren/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-christian-grandparent-in-the-load-shedding/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-christian-in-the-law-firm/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-christian-mother-of-young-adults-johannesburg/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-christian-stem-student/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-christian-who-doesnt-give-money/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-christian-who-is-doubting/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-christian-who-moved-to-south-africa/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-foreign-christian-in-south-africa/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-neighbourhood-watch-and-the-christian/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-single-christian-mother-in-sandton/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-south-african-christian-and-the-divorce/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-teacher-who-is-also-a-christian/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/the-widower-in-johannesburg/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/time-management-for-the-busy-christian/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/traffic-and-the-christian-driver/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/volunteering-burnout/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/when-the-language-changes-in-church/', lastmod: 'DRAFT-2026-10-10' },
    { url: '/blog/when-the-pastor-quits/', lastmod: 'DRAFT-2026-10-10' },
  ];

  // Filter out DRAFT- entries from the public sitemap. DRAFT-2026-10-10
  // is the sentinel we use to mark posts that have not yet been released.
  // The release script strips the prefix when a batch is promoted.
  const allPages = [
    ...staticPages,
    ...seoLandingPages.map((p) => ({ ...p, priority: '0.8', changefreq: 'monthly' })),
    ...blogPosts
      .filter((p) => !p.lastmod?.startsWith('DRAFT-'))
      .map((p) => ({
        ...p,
        lastmod: p.lastmod?.replace(/^DRAFT-/, '') ?? p.lastmod,
        priority: '0.7',
        changefreq: 'monthly',
      })),
  ];

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${allPages
    .map(
      (page) => `  <url>
    <loc>${siteUrl}${page.url}</loc>
    <lastmod>${page.lastmod ?? now}</lastmod>
    <changefreq>${page.changefreq}</changefreq>
    <priority>${page.priority}</priority>
  </url>`
    )
    .join('\n')}
</urlset>`;

  return new Response(xml, {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
    },
  });
};
